php artisan make:model chitiethoadonnhaps
php artisan make:model chitiethoadons
php artisan make:model chuyenmucs
php artisan make:model hoadonnhaps
php artisan make:model hoadons
php artisan make:model khachhang
php artisan make:model loaitaikhoan
php artisan make:model nhaphanphois
php artisan make:model sanphams
php artisan make:model sanphams_nhaphanphois
php artisan make:model size
php artisan make:model taikhoan